config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "theses#index"

  resources :users
  resources :theses
  resources :tasks
  resources :comments

  namespace :admin do
    root "static_pages#home"
    get "/theses_type", to: "static_pages#home"
    resources :users
    resources :tasks
    resources :comments
    resources :theses do
      member do
        patch :approved
        patch :rejected
      end
    end
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :thesis
  has_many :comments

  validates :name, presence: true

  enum status: [:Progressing, :Done]
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController
  before_action :authenticated_admin

  def index
    @tasks = Task.where thesis_id: params[:thesis_id]
  end

  def show
    @task = Task.find_by id: params[:id]
    @comments = @task.comments.order created_at: :desc
    @comment = Comment.new
  end

  private

  def load_task
    @task = Task.find_by id: params[:id]
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user
  before_action :admin?
  before_action :load_task, only: [:edit, :update, :destroy]
  before_action :check_user, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.where thesis_id: params[:thesis_id]
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new task_params
    if @task.save
      redirect_to tasks_path thesis_id: @task.thesis_id
    else
      render :new
    end
  end

  def show
    @task = Task.find_by id: params[:id]
    @comments = @task.comments.order created_at: :desc
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @task.update_attributes task_params
      redirect_to tasks_path thesis_id: @task.thesis_id
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path thesis_id: @task.thesis.id
  end

  private

  def task_params
    params.require(:task).permit(:name, :status, :thesis_id)
  end

  def load_task
    @task = Task.find_by id: params[:id]
  end

  def check_user
    redirect_to user_path(current_user) unless current_user == Task.find_by(id: params[:id]) && User.find_by(id: Task.find_by(id: params[:id]).user_id)
  end
end

app/views/admin/tasks/index.html.erb
<div class="wrapper">
  <nav id="sidebar">
    <div class="sidebar-header">
      <h3>Thesis Management System</h3>
    </div>
    <ul class="list-unstyled components">
      <li>
        <%= link_to "Profile", admin_user_path(current_user) %>
      </li>
     <li class="active">
        <%= link_to "Thesis", admin_theses_path %>
      </li>
      <li>
        <%= link_to "Log out", logout_path, method: :delete %>
      </li>
    </ul>
  </nav>
</div>
<div id="content">
  <div class="table-title">
    <h1>Tasks</h1>
  </div>
  <table class="table table-striped task">
    <tr>
      <th>Task name</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
    <% if @tasks.present? %>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to "#{task.name}", admin_task_path(task) %></td>
          <td><span class="<%= task.status %>"><%= task.status %></span></td>
          <td>
            <%= link_to admin_task_path(task), class: "btn btn-primary", title: "Show" do %>
              <i class="fa fa-eye" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
  <%= link_to "Back", admin_thesis_path(id: params[:thesis_id]), class: "btn btn-primary edit-thesis" %>
</div>

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.6.8-fix/jquery.nicescroll.min.js"></script>

app/views/admin/tasks/show.html.erb
<div class="wrapper">
  <nav id="sidebar">
    <div class="sidebar-header">
      <h3>Thesis Management System</h3>
    </div>
    <ul class="list-unstyled components">
      <li>
        <%= link_to "Profile", admin_user_path(current_user) %>
      </li>
     <li class="active">
        <%= link_to "Theses", admin_theses_type_path %>
      </li>
      <li>
        <%= link_to "Log out", logout_path, method: :delete %>
      </li>
    </ul>
  </nav>
</div>
<div id="content">
  <div class="table-title">
    <h1><%= @task.name %></h1>
  </div>
  <h5>Status: <span class="<%= @task.status %>"><%= @task.status %></span></h5>

  <div class="container">
    <div class="row">
      <div >
        <h3>Comment:</h3>
      </div>
      <%= form_for @comment, {url: admin_comments_path, method: :post} do |f| %>
        <div class="form-group">
          <%= f.text_field :content, class: "form-control" %>
        </div>
        <%= f.hidden_field :task_id, value: @task.id %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="form-group">
          <%= f.submit "Comment",  class: "btn btn-primary" %>
        </div>
      <% end %>
      <% if @comments.count > 0 %>
        <% @comments.each do |comment| %>
          <div class="row">
            <div class="col-sm-1">
              <div class="thumbnail">
                <img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
              </div>
            </div>
            <div class="col-sm-5">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <strong><%= comment.user.name %></strong>
                  <span class="text-muted"><%= time_ago_in_words comment.created_at %> ago</span>
                  <%= link_to admin_comment_path(comment), method: :delete, class: "pull-right", title: "Delete" do %>
                    <i class="fa fa-trash" aria-hidden="true"></i>
                  <% end %>
                </div>
                <div class="panel-body">
                  <%= comment.content %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

</div>

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.6.8-fix/jquery.nicescroll.min.js"></script>