config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "theses#index"

  resources :users
  resources :theses
  resources :tasks
  resources :comments

  namespace :admin do
    root "static_pages#home"
    get "/theses_type", to: "static_pages#home"
    resources :users
    resources :tasks
    resources :comments
    resources :theses do
      member do
        patch :approved
        patch :rejected
      end
    end
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

  enum role: [:student, :admin]

  has_many :thesis
  has_many :comments

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticated_admin
  before_action :load_user

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      redirect_to admin_user_path @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def load_user
    @user = User.find_by id: params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :admin?
  before_action :load_user
  before_action :check_user

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def load_user
    @user = User.find_by id: params[:id]
    redirect_to login_path unless @user
  end

  def check_user
    redirect_to user_path(current_user) unless current_user == User.find_by(id: params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="wrapper">
  <nav id="sidebar">
    <div class="sidebar-header">
      <h3>Thesis Management System</h3>
    </div>
    <ul class="list-unstyled components">
      <li class="active">
        <%= link_to "Profile", admin_user_path(current_user) %>
      </li>
     <li>
        <%= link_to "Theses", admin_theses_type_path %>
      </li>
      <li>
        <%= link_to "Log out", logout_path, method: :delete %>
      </li>
    </ul>
  </nav>
</div>
<div id="content">
  <div class="table-title">
    <h1>Edit Profile</h1>
  </div>
  <%= form_for [:admin, @user] do |f| %>
    <%= render "shared/error_messages", object: @user %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= link_to "Back", admin_user_path(@user), class: "btn btn-primary" %>
    <%= f.submit "Update", class: "btn btn-success"  %>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="wrapper">
  <nav id="sidebar">
    <div class="sidebar-header">
      <h3>Thesis Management System</h3>
    </div>
    <ul class="list-unstyled components">
      <li class="active">
        <%= link_to "Profile", admin_user_path(current_user) %>
      </li>
     <li>
        <%= link_to "Theses", admin_theses_type_path %>
      </li>
      <li>
        <%= link_to "Log out", logout_path, method: :delete %>
      </li>
    </ul>
  </nav>
</div>
<div id="content">
  <div class="table-title">
    <h1>Profile</h1>
  </div>
  <table class="table table-striped">
    <tbody>
      <tr>
        <td>Student code</td>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <td>Name</td>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <td>Email</td>
        <td><%= @user.email %></td>
      </tr>
        <td>Role</td>
        <td><%= @user.role %></td>
      </tr>
    </tbody>
  </table>
  <%= link_to "Edit profile", edit_admin_user_path(@user), class: "btn btn-primary" %>
</div>

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.6.8-fix/jquery.nicescroll.min.js"></script>