config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "theses#index"

  resources :users
  resources :theses
  resources :tasks
  resources :comments

  namespace :admin do
    root "static_pages#home"
    get "/theses_type", to: "static_pages#home"
    resources :users
    resources :tasks
    resources :comments
    resources :theses do
      member do
        patch :approved
        patch :rejected
      end
    end
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/controllers/admin/theses_controller.rb
class Admin::ThesesController < ApplicationController
  before_action :authenticated_admin
  before_action :load_thesis, except: [:index, :new, :create]

  def index
    @theses = Thesis.where thesis_type: params[:type]
  end

  def new
    @thesis = Thesis.new
    @users = User.where(role: "student")
  end

  def create
    @thesis = Thesis.new thesis_params
    if @thesis.save
      redirect_to admin_theses_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    @users = User.where(role: "student")
    @types = ["Specialized Project", "Graduation Thesis", "Basic Project"]
  end

  def update
    if @thesis.update_attributes thesis_params
      flash[:success] = "Updated"
      redirect_to admin_thesis_path @thesis
    else
      flash[:danger] = "Cannot update"
      render :edit
    end
  end

  def destroy
    @thesis.destroy
    redirect_to admin_theses_path
  end

  def approved
    @thesis.update_attributes status: "approved"
    redirect_to admin_theses_path
  end

  def rejected
    @thesis.update_attributes status: "rejected"
    redirect_to admin_theses_path
  end

  private

  def load_thesis
    @thesis = Thesis.find_by id: params[:id]
  end

  def thesis_params
    params.require(:thesis).permit(:name, :description, :progress, :user_id, :thesis_type)
  end
end

app/controllers/theses_controller.rb
class ThesesController < ApplicationController
  before_action :logged_in_user
  before_action :admin?
  before_action :load_thesis, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:show, :edit, :update, :destroy]

  def index
    @theses = Thesis.where user_id: [current_user.id, nil]
  end

  def show
  end

  def new
    @thesis = Thesis.new
  end

  def create
    @thesis = Thesis.new thesis_params
    if @thesis.save
      redirect_to theses_path
    else
      render :new
    end
  end

  def edit
    @percent = %w[0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100]
    @types = ["Specialized Project", "Graduation Thesis", "Basic Project"]
  end

  def update
    if @thesis.update_attributes thesis_params
      flash[:success] = "Updated"
      redirect_to @thesis
    else
      flash[:danger] = "Cannot update"
      render :edit
    end
  end

  def destroy
    @thesis.destroy
    redirect_to theses_path
  end

  private

  def thesis_params
    params.require(:thesis).permit(:name, :description, :progress, :user_id)
  end

  def load_thesis
    @thesis = Thesis.find_by id: params[:id]
  end

  def check_user

    redirect_to user_path(current_user) unless Thesis.find_by(id: params[:id]) && urrent_user == User.find_by(id: Thesis.find_by(id: params[:id]).user_id)
  end
end

app/views/admin/theses/edit.html.erb
<div class="wrapper">
  <nav id="sidebar">
    <div class="sidebar-header">
      <h3>Thesis Management System</h3>
    </div>
    <ul class="list-unstyled components">
      <li>
        <%= link_to "Profile", admin_user_path(current_user) %>
      </li>
     <li class="active">
        <%= link_to "Theses", admin_theses_type_path %>
      </li>
      <li>
        <%= link_to "Log out", logout_path, method: :delete %>
      </li>
    </ul>
  </nav>
</div>
<div id="content">
  <div class="table-title">
    <h1>Edit Thesis</h1>
  </div>
  <%= form_for [:admin, @thesis] do |f| %>
    <%= render "shared/error_messages", object: @thesis %>
    <div class="form-group">
      <%= f.label :name  %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description  %>
      <%= f.text_area :description, rows: 10, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :"type:" %>
      <%= f.select :thesis_type, @types, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :"assignee:"  %>
      <%= f.select :user_id, options_for_select(@users.collect {|user| [user.name, user.id]},
        selected: f.object.user.id), include_blank: true %>
    </div>
    <br>
    <%= link_to "Back", admin_thesis_path(@thesis), class: "btn btn-primary" %>
    <%= f.submit "Done", class: "btn btn-primary" %>
  <% end %>
</div>

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.6.8-fix/jquery.nicescroll.min.js"></script>

app/views/admin/theses/index.html.erb
<div class="wrapper">
  <nav id="sidebar">
    <div class="sidebar-header">
      <h3>Thesis Management System</h3>
    </div>
    <ul class="list-unstyled components">
      <li>
        <%= link_to "Profile", admin_user_path(current_user) %>
      </li>
     <li class="active">
        <%= link_to "Theses", admin_theses_type_path %>
      </li>
      <li>
        <%= link_to "Log out", logout_path, method: :delete %>
      </li>
    </ul>
  </nav>
</div>
<div id="content">
  <div class="table-title">
    <h1>Theses</h1>
  </div>
  <div id="new-task">
    <%= link_to "New Thesis", new_admin_thesis_path, class: "btn btn-primary edit-task" %>
  </div>
  <table class="table table-striped task">
    <tr>
      <th>Student name</th>
      <th>Thesis name</th>
      <th>Status</th>
      <th>Action</th>
      <th>Type</th>
    </tr>
    <% if @theses.present? %>
      <% @theses.each do |thesis| %>
        <tr>
          <td>
            <% if thesis.user.present? %>
              <%= thesis.user.name %>
            <% end %>
          </td>
          <td><%= link_to "#{thesis.name}", admin_thesis_path(thesis) %></td>
          <td >
            <% if thesis.user.present? %>
              <span class="label <%= thesis.status %>"><%= thesis.status %></span>
            <% end %>
          </td>
          <td>
            <%= link_to edit_admin_thesis_path(thesis), class: "btn btn-primary", title: "Edit" do %>
              <i class="fa fa-pencil-square" aria-hidden="true"></i>
            <% end %>
            <%= link_to admin_thesis_path(thesis), method: :delete, class: "btn btn-danger", title: "Delete" do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
          </td>
          <td><%= thesis.thesis_type %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.6.8-fix/jquery.nicescroll.min.js"></script>

app/views/admin/theses/new.html.erb
<div class="wrapper">
  <nav id="sidebar">
    <div class="sidebar-header">
      <h3>Thesis Management System</h3>
    </div>
    <ul class="list-unstyled components">
      <li>
        <%= link_to "Profile", admin_user_path(current_user) %>
      </li>
     <li class="active">
        <%= link_to "Theses", admin_theses_type_path %>
      </li>
      <li>
        <%= link_to "Log out", logout_path, method: :delete %>
      </li>
    </ul>
  </nav>
</div>
<div id="content">
  <div class="table-title">
    <h1>New Thesis</h1>
  </div>
  <%= form_for [:admin, @thesis] do |f| %>
    <%= render "shared/error_messages", object: @thesis %>
    <div class="form-group">
      <%= f.label :name  %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description  %>
      <%= f.text_area :description, rows: 10, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :"type:" %>
      <%= f.select :thesis_type, @types, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :"assignee:"  %>
      <%= f.select :user_id, options_for_select(@users.collect {|user| [user.name, user.id]}), include_blank: true %>
    </div>
    <br>
    <%= f.submit "Create", class: "btn btn-primary"  %>
  <% end %>
</div>

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.6.8-fix/jquery.nicescroll.min.js"></script>

app/views/admin/theses/show.html.erb
<div class="wrapper">
  <nav id="sidebar">
    <div class="sidebar-header">
      <h3>Thesis Management System</h3>
    </div>
    <ul class="list-unstyled components">
      <li>
        <%= link_to "Profile", admin_user_path(current_user) %>
      </li>
     <li class="active">
        <%= link_to "Theses", admin_theses_type_path %>
      </li>
      <li>
        <%= link_to "Log out", logout_path, method: :delete %>
      </li>
    </ul>
  </nav>
</div>
<div id="content">
  <div class="table-title">
    <h1><%= @thesis.name %></h1>
  </div>
  <h5>Status: <span class="btn <%= @thesis.status %>"><%= @thesis.status %></span></h5>
  <hr/>
  <div>
    <h4>Description</h4>
    <%= @thesis.description %>
    <hr/>
  </div>
  <div>
    <h4>Progress</h4>
    <%= @thesis.progress %>
  <hr/>
  </div>
  <div>
    <% if @thesis.status == "approved" %>
      <%= link_to "All Task", admin_tasks_path(thesis_id: @thesis.id), class: "btn btn-default" %>
    <% end %>
  </div>
  <br/>
  <% if @thesis.user.present? %>
    <% if @thesis.status == "pending" %>
      <%= link_to "Approve", approved_admin_thesis_path(@thesis), method: :patch, class: "btn btn-success edit-thesis" %>
      <%= link_to "Reject", rejected_admin_thesis_path(@thesis), method: :patch, class: "btn btn-danger edit-thesis" %>
      <hr>
    <% end %>
  <% end %>
  <%= link_to "Back", admin_theses_path, class: "btn btn-primary edit-thesis" %>
  <%= link_to "Edit", edit_admin_thesis_path(@thesis), class: "btn btn-primary edit-thesis" %>
</div>

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.6.8-fix/jquery.nicescroll.min.js"></script>